### ISSUE TITLE
Auto-install for Indonesian Language

### ISSUE THREAD

**Issue by arung-agamani** [darkGrimoire/ta1-latex-itb#1]
Usage of Bahasa language is not included into install script, which causes error when doing `make` command.
Error output :
```! Package babel Error: Unknown option `bahasa'. Either you misspelled it
(babel)                or the language definition file bahasa.ldf was not found```

It can be fixed by adding the below script when installing required packages

`sudo apt-get install texlive-lang-other`

**Comment by darkGrimoire** [comment]
thanks, I think I missed it because I was doing texlive full install on my machine

**Comment by darkGrimoire** [comment]
fixed in commit https://github.com/darkGrimoire/ta1-latex-itb/commit/f236ae7515af66c8be8a1f7109050c963a421e8d
